name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:

  job_release:
    name: Create Release and Upload to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Get tag
      id: tag
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Build
      id: build
      run: |
        python setup.py build sdist bdist_wheel

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.tag.outputs.tag }}
        prerelease: false
        draft: true
        files: |
          dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        verbose: true
